import docx
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

class MSWord():
    def __init__(self, sp_name, team_name):
        self.doc = docx.Document()
        MSWord.create_cover_page(self, sp_name, team_name)

    def save(self):
        self.doc.save("Demo TOL.docx")

    def create_cover_page(self, sp_name, team_name):
        for i in range(6):
            self.doc.add_paragraph()

        sp_name_par = self.doc.add_paragraph()
        sp_name_run = sp_name_par.add_run(sp_name)
        sp_name_run.font.size = Pt(16)
        sp_name_par.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        sp_name_run.font.name="Cambria"

        title = self.doc.add_paragraph()
        title_run = title.add_run("TOL")
        title_run.font.size = Pt(66)
        title_run.bold = True
        title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        title_run.font.name="Ericsson Capital TT"

        team_name_par = self.doc.add_paragraph()
        team_name_run = team_name_par.add_run(team_name)
        team_name_run.font.size = Pt(16)
        team_name_par.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        team_name_run.font.name="Cambria"

        for i in range(13):
            self.doc.add_paragraph()

        footnote = self.doc.add_paragraph()
        footnote_run = footnote.add_run("Generated by TOLBOT™")
        footnote_run.font.size = Pt(10)
        footnote.alignment = WD_PARAGRAPH_ALIGNMENT.RIGHT
        footnote_run.font.name="Ericsson Hilda Mono ExtraLight"

    def create_statistic_page(self, suites, tests):
        test_count = self.doc.add_paragraph()
        test_count_run = test_count.add_run(f"Total test count: {len(tests)}")
        test_count_run.font.size = Pt(16)
        test_count.alignment = WD_PARAGRAPH_ALIGNMENT.LEFT
        test_count_run.font.name="Ericsson Capital TT"

        self.doc.add_paragraph()
        self.doc.add_paragraph()

        table_title = self.doc.add_heading("MCT Suites Impacted", level=1)
        table_title_run = table_title.runs[0]
        table_title_run.font.size = Pt(18)
        table_title_run.font.name="Ericsson Hilda"
        table_title_run.font.italic = True
        table_title.paragraph_format.space_after = Pt(10)

        files = list(suites.keys())
        suite_names = []
        for suite_name in files:
            if '/COMMIT_MSG' in suite_name:
                continue
            suite_names.append(suite_name)

        suites_table = self.doc.add_table(rows=len(suite_names),cols=1)
        for i, row_data in enumerate(suite_names):
            suites_table.cell(i,0).text = row_data

        self.doc.add_page_break()

    def fill_test_data(self, repo, tests):
        repo_name_heading = self.doc.add_heading(repo, level=1)
        repo_name_run = repo_name_heading.runs[0]
        repo_name_run.font.name = 'Ericsson Hilda'
        repo_name_run.font.size = Pt(20)
        repo_name_heading.paragraph_format.space_after = Pt(12)

        for test in tests:
            for key, value in test.items():
                if key == "NAME":
                    test_name_heading = self.doc.add_heading(value, level=2)
                    test_name_run = test_name_heading.runs[0]
                    test_name_run.font.name = 'Ericsson Hilda ExtraLight'
                    test_name_run.font.size = Pt(18)
                    test_name_heading.paragraph_format.space_after = Pt(10)

                else:
                    test_data_heading = self.doc.add_heading(key, level = 3)
                    test_data_run = test_data_heading.runs[0]
                    test_data_run.font.name = 'Ericsson Hilda Light'
                    test_data_run.font.size = Pt(13)
                    test_data_run.font.italic = True
                    test_data_run.font.bold = False
                    test_data_heading.paragraph_format.space_before = Pt(3)
                    test_data_heading.paragraph_format.space_after = Pt(3)

                    test_text = self.doc.add_paragraph()
                    test_text_run = test_text.add_run(value)
                    test_text_run.font.size = Pt(10)
                    test_text_run.font.name="Ericsson Hilda"
            self.doc.add_page_break()