import docx
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

def create_cover_page(doc):

    for i in range(6):
        doc.add_paragraph()

    sp_name = doc.add_paragraph()
    sp_name_run = sp_name.add_run("SPXXXX-X")
    sp_name_run.font.size = Pt(16)
    sp_name.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    sp_name_run.font.name="Cambria"

    title = doc.add_paragraph()
    title_run = title.add_run("TOL")
    title_run.font.size = Pt(66)
    title_run.bold = True
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    title_run.font.name="Ericsson Capital TT"

    team_name = doc.add_paragraph()
    team_name_run = team_name.add_run("xFT-XXXXXX")
    team_name_run.font.size = Pt(16)
    team_name.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    team_name_run.font.name="Cambria"

    for i in range(13):
        doc.add_paragraph()

    footnote = doc.add_paragraph()
    footnote_run = footnote.add_run("Generated by TOLBOT™")
    footnote_run.font.size = Pt(10)
    footnote.alignment = WD_PARAGRAPH_ALIGNMENT.RIGHT
    footnote_run.font.name="Ericsson Hilda Mono ExtraLight"

def create_statistic_page(doc, tests):
    test_count = doc.add_paragraph()
    test_count_run = test_count.add_run(f"Total test count: {len(tests)}")
    test_count_run.font.size = Pt(16)
    test_count.alignment = WD_PARAGRAPH_ALIGNMENT.LEFT
    test_count_run.font.name="Ericsson Capital TT"

def fill_test_data(doc, tests):
    for test in tests:
        for key, value in test.items():
            if key == "NAME":
                test_name_heading = doc.add_heading(value, level=2)
                test_name_run = test_name_heading.runs[0]
                test_name_run.font.name = 'Ericsson Hilda ExtraLight'
                test_name_run.font.size = Pt(18)
                test_name_heading.paragraph_format.space_after = Pt(5)

            else:
                test_data_heading = doc.add_heading(key, level = 3)
                test_data_run = test_data_heading.runs[0]
                test_data_run.font.name = 'Ericsson Hilda Light'
                test_data_run.font.size = Pt(13)
                test_data_run.font.italic = True
                test_data_run.font.bold = False
                test_data_heading.paragraph_format.space_before = Pt(3)
                test_data_heading.paragraph_format.space_after = Pt(3)

                test_text = doc.add_paragraph()
                test_text_run = test_text.add_run(value)
                test_text_run.font.size = Pt(10)
                test_text_run.font.name="Ericsson Hilda"
        doc.add_page_break()


def write(tests):
    doc = docx.Document()
    create_cover_page(doc)
    create_statistic_page(doc, tests)
    doc.add_page_break()
    fill_test_data(doc, tests)

    doc.save("Demo TOL.docx")
